### ISSUE TITLE
Resolution slider

### ISSUE THREAD

**Issue by NicolasRGit** [aefly/IVAIO#1]
Hi! tryed the mod and worked perfectly, was working for a deadzone mouse fix and this did the trick! The problem that im facing now its that it dosnt let me chose the right resolution for the game. I was playing perfectly at 2560x1440 previously, but now after the mod the slider only goes to a 1200x800 resolution (or something like that) unplayable for me, im tryng to fix it.

**Comment by aefly** [comment]
Hi, this issue is from [dxvk](https://github.com/doitsujin/dxvk/issues/1831), you can try to delete it from your file (d3d9.dll and dxgi.dll), then launch your game and try to see if you can can change to your native resolution
